name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
   runs-on: macos-11
   steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild clean build -project "Notch Simulator/Notch Simulator.xcodeproj" CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO PRODUCT_BUNDLE_IDENTIFIER="com.JinyuMeng.Notch-Simulator" -sdk macosx -scheme "Notch Simulator" -configuration Release -derivedDataPath build
          zip -r Notch\ Simulator.zip Notch\ Simulator.app
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
         name: Notch Simulator.app
         path: "Notch\ Simulator/Notch\ Simulator.zip"
